[package]
name = "agent-openai-gpt-oss-20b"
version = "0.1.0"
edition = "2024"

[dependencies]
openai_api_rust = "0.1.9"
openai-harmony = { git = "https://github.com/openai/harmony" }
anyhow = "1.0"
serde_json = "1.0"
